#define FOVK_0            0
#define FOVK_1            1
#define FOVK_2            2
#define FOVK_3            3
#define FOVK_4            4
#define FOVK_5            5
#define FOVK_6            6
#define FOVK_7            7
#define FOVK_8            8
#define FOVK_9            9
#define FOVK_a            10
#define FOVK_b            11
#define FOVK_c            12
#define FOVK_d            13
#define FOVK_e            14
#define FOVK_f            15
#define FOVK_g            16
#define FOVK_h            17
#define FOVK_i            18
#define FOVK_j            19
#define FOVK_k            20
#define FOVK_l            21
#define FOVK_m            22
#define FOVK_n            23
#define FOVK_o            24
#define FOVK_p            25
#define FOVK_q            26
#define FOVK_r            27
#define FOVK_s            28
#define FOVK_t            29
#define FOVK_u            30
#define FOVK_v            31
#define FOVK_w            32
#define FOVK_x            33
#define FOVK_y            34
#define FOVK_z            35
#define FOVK_SPACE        36
#define FOVK_EXCLAIM      37
#define FOVK_QUOTEDBL     38
#define FOVK_HASH         39
#define FOVK_DOLLAR       40
#define FOVK_AMPERSAND    41
#define FOVK_QUOTE        42
#define FOVK_LEFTPAREN    43
#define FOVK_RIGHTPAREN   44
#define FOVK_ASTERISK     45
#define FOVK_PLUS         46
#define FOVK_COMMA        47
#define FOVK_MINUS        48
#define FOVK_PERIOD       49
#define FOVK_SLASH        50
#define FOVK_COLON        51
#define FOVK_SEMICOLON    52
#define FOVK_LESS         53
#define FOVK_EQUALS       54
#define FOVK_GREATER      55
#define FOVK_QUESTION     56
#define FOVK_AT           57
#define FOVK_LEFTBRACKET  58
#define FOVK_BACKSLASH    59
#define FOVK_RIGHTBRACKET 60
#define FOVK_CARET        61
#define FOVK_UNDERSCORE   62
#define FOVK_BACKQUOTE    63
#define FOVK_KP_MULTIPLY  64
#define FOVK_KP_PLUS      65
#define FOVK_KP_MINUS     66
#define FOVK_KP_PERIOD    67
#define FOVK_KP_DIVIDE    68
#define FOVK_KP_EQUALS    69
#define FOVK_DELETE       70
#define FOVK_ESCAPE       71
#define FOVK_BACKSPACE    72
#define FOVK_KP_ENTER     73
#define FOVK_RETURN       74
#define FOVK_TAB          75
#define FOVK_F1           76
#define FOVK_F2           77
#define FOVK_F3           78
#define FOVK_F4           79
#define FOVK_F5           80
#define FOVK_F6           81
#define FOVK_F7           82
#define FOVK_F8           83
#define FOVK_F9           94
#define FOVK_F10          85
#define FOVK_F11          86
#define FOVK_F12          87
#define FOVK_F13          88
#define FOVK_F14          89
#define FOVK_F15          90
#define FOVK_SYSREQ       91
#define FOVK_BREAK        92
#define FOVK_CAPSLOCK     93
#define FOVK_CLEAR        94
#define FOVK_DOWN         95
#define FOVK_END          96
#define FOVK_EURO         97
#define FOVK_HELP         98
#define FOVK_HOME         99
#define FOVK_INSERT       100
#define FOVK_KP0          101
#define FOVK_KP1          102
#define FOVK_KP2          103
#define FOVK_KP3          104
#define FOVK_KP4          105
#define FOVK_KP5          106
#define FOVK_KP6          107
#define FOVK_KP7          108
#define FOVK_KP8          109
#define FOVK_KP9          110
#define FOVK_LALT         111
#define FOVK_LEFT         112
#define FOVK_LCTRL        113
#define FOVK_LMETA        114
#define FOVK_LSHIFT       115
#define FOVK_LSUPER       116
#define FOVK_MENU         117
#define FOVK_MODE         118
#define FOVK_NUMLOCK      119
#define FOVK_PAGEDOWN     120
#define FOVK_PAGEUP       121
#define FOVK_PAUSE        122
#define FOVK_POWER        123
#define FOVK_PRINT        124
#define FOVK_RALT         125
#define FOVK_RIGHT        126
#define FOVK_RCTRL        127
#define FOVK_RMETA        128
#define FOVK_RSHIFT       129
#define FOVK_RSUPER       130
#define FOVK_SCROLLOCK    131
#define FOVK_UP           132
#define FOVK_MOUSE0       133 // left mouse button
#define FOVK_MOUSE1       134 // right mouse button
#define FOVK_MOUSE2       135 // middle mouse button
#define FOVK_MOUSE3       136
#define FOVK_MOUSE4       137
#define FOVK_MOUSE5       138
#define FOVK_MOUSE6       139
#define FOVK_MOUSE7       140
#define FOVK_MOUSE8       141
#define FOVK_MOUSE9       142

#define FOVK_UNKNOWN      255
